---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIKEY: AgClM08z98110trzf9EWBaNlYwWoGAIUUNEoNBYf8zzCEoZlmOO+X+p4xa9u31SIrM1wOdD2HZXJbyq0hWSdjSdSxrCUGpL+5PCn5fLvEE5VtTyfhG8dLfk7KmjV7Pbr2oxbGmvHzCujBgO+UhIcCiGTUjUQ2bIw6sREDBoR0rcOVC6QZJlzGnjLocG3a3EwOpBmhguRgeLXTbNNx97PNOmicAq6vhOGTPeSHtQV5jn0WVGpIFl3j9XvF8ev/Zo+yNvsYQJ820RYrAMTCSqa7SyTL+jMc6H9efO7MQ6LEJk5/n521GmC0vtz4UjN/mOnurzRQxZ11/iZR0qLmlHzLe0qx7ZRt2z98SNX40HLgbwOlitA91sONQVCBBmnqRqYokdg87KuQu4gMqxxbha6LpRHhPPV0lohMvuucLRfxrh/qcXCrBexTehkdi8vRIiveu7lYJTYrOON6MUP2zbGipdkCYeN5SxpmAFS/8Qnb1FFCPpk4+sL58wRu3fc0tmMPefOrfEdvwpF17DvD8et9gp46k28ebvW11SCs+FWj10ERLbydi/qmmp93msEgHjMSCMgKmYohZuofUSRnzdnajTNlLpd+vDlvyP8GqThDXTEMj6SEE/Pyee3DtYPzXjovHcMHfK+JIz8zl8F5X+fgR2SKKUes1amueoXAv5SZtORUYib0QLemQ0PcRFKm3GvPzzqXDh98o1XaKC3WZIrfKk2Ov/lOTf7Ttw6SfRMoUHwE836ksAOP1Ye3wEFzF7e7yWlZA==
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: default
    type: Opaque
